=== Jordanspector1/examples--principles-of-databases--cs-365--uhart/Xml1/student.dtd
<!-- Uhart is my root element. It has to hold one or more students -->
<!ELEMENT Uhart (student+)>

<!-- A student will always have a names element -->
<!ELEMENT student (names)>

<!-- Attributes for students -->
<!ATTLIST student
  studid ID #REQUIRED
  Yr (fresh|soph|jun|sen) #REQUIRED>

  <!-- First/ last name -->
  <!ELEMENT names (first, last)>


<!-- first name is just text -->
  <!ELEMENT first (#PCDATA)>

  <!-- last name is just text -->
  <!ELEMENT last (#PCDATA)>


<!-- Add the rest of the required student info as attributes (keep structure the same) -->
<!ATTLIST student

  <!-- enrollment status must be one of these -->
  status (full-time|part-time|graduated|withdrawn) #REQUIRED

  <!-- optional preferred name shown to the user -->
  preferredName CDATA #IMPLIED

  <!-- contact info -->
  email CDATA #REQUIRED
  phone CDATA #REQUIRED


  <!-- academics -->
  gpa CDATA #IMPLIED
  major CDATA #REQUIRED
  minor CDATA #IMPLIED
  advisor CDATA #REQUIRED

  <!-- dates in ISO format YYYY-MM-DD -->
  initialEnrollmentDate CDATA #REQUIRED
  graduationDate CDATA #IMPLIED>

=== Jordanspector1/examples--principles-of-databases--cs-365--uhart/Xml1/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE Uhart SYSTEM "student.dtd">

<Uhart>

<student studid="JORD" Yr="sen" status="full-time" prefname="Jordan" email="jspector@hartford.edu" phone="5083616477" gpa="3.14" major="CS" minor="None" advisor="Carolyn Roseine" initialenrollmentdate="2020-11-12" graddate="2025-01-04">
    <names>
      <first>Jordan</first>
      <last>Spector</last>
    </names>
  </student>

<student studid="DARE" Yr="soph" status="part-time" prefname="Johnny" email="rururu@hartford.edu" phone="1219219212" gpa="1.9" major="Psychology" minor="Data Science" advisor="Jordan Spector" initialenrollmentdate="2020-11-12">
    <names>
      <first>Ruby</first>
      <last>Stein</last>
    </names>
  </student>

<student studid="RYAN" Yr="jun" status="full-time" prefname="REPLACE" email="rryan@hartford.edu" phone="112919212" gpa="3.5" major="Photography" minor="Psychology" advisor="Roy Venegas " initialenrollmentdate="2020-11-12">
    <names>
      <first>Ryan</first>
      <last>Levitan</last>
    </names>
  </student>

</Uhart>
